### ISSUE TITLE
Restricting access to external services

### ISSUE THREAD

**Issue by Cosaquee** [compiler-explorer/infra#204]
Currently the Security Group rules defined [here](https://github.com/mattgodbolt/compiler-explorer-image/blob/48459028ef4644834119a0426a19ae6376e6c4dc/terraform/security.tf#L15) allows access to the Internet without any filtering. There is an option to programmatically obtain the CIDR ranges of Github networks:

```
/personal/git/compiler-explorer-image(master ✔) curl https://api.github.com/meta
{
  "verifiable_password_authentication": true,
  "hooks": [
    "192.30.252.0/22",
    "185.199.108.0/22",
    "140.82.112.0/20"
  ],
  "git": [
    "192.30.252.0/22",
    "185.199.108.0/22",
    "140.82.112.0/20",
    "13.229.188.59/32",
    "13.250.177.223/32",
    "18.194.104.89/32",
    "18.195.85.27/32",
    "35.159.8.160/32",
    "52.74.223.119/32"
  ],
  "pages": [
    "192.30.252.153/32",
    "192.30.252.154/32",
    "185.199.108.153/32",
    "185.199.109.153/32",
    "185.199.110.153/32",
    "185.199.111.153/32"
  ],
  "importer": [
    "54.87.5.173",
    "54.166.52.62",
    "23.20.92.3"
  ]
}
```

We can just hardcode those values and check regularly or use some custom Terraform providers magic to have it always up to date.

I'm not sure if there is a way to obtain IP addresses for DockerHub, but will investigate.

**Comment by Cosaquee** [comment]
The option with Docker would be to maybe move to Amazon hosted registry and use IAM roles and policies to secure it. This would allow us to lock down nodes.

**Comment by mattgodbolt** [comment]
There's also Ubuntu servers for access to `apt update` etc (though we could prevent that). It would be great to restrict the internet access of nodes, but I'm scared of accidentally locking out a bunch of useful things :)

This is still worth pursuing. I hope to move away from Docker, so that might become less of an issue. Docker registry is an option but would be a big change (all the images we use are auto-built on docker hub currently).

**Comment by mattgodbolt** [comment]
See also #62

**Comment by apmorton** [comment]
going to close this as a dup of #62
